* 🚀 ONBOARD – Build your own vanilla Emacs

*Portable Emacs config without any 3rd-party packages*

Overwhelmed by the complexity of Emacs starter distributions like Doom-Emacs or Spacemacs?
You want to build your Emacs config bottom-up but not forget easy-to-miss basics?

The goal of this Emacs config is to offer a clean slate to build upon. It stays as close as possible to vanilla Emacs, but offers some convenience and a better look, without relying on other packages. All built-in – all ONBOARD.

** Getting started

*** New Emacs user without own config files?

1. Download init-onboard.el
2. Rename it to .emacs
3. Move it to your home directory and start Emacs
or
1. Download init-onboard.el
2. Rename it to init.el
3. Move it to ~/.emacs.d directory and start Emacs

*** Emacs user with existing .emacs or ~/.emacs.d/init.el file?

1. Download init-onboard.el
2. Open a terminal to try it out
3. Run the shell command: emacs -Q --load ~/path/to/init-onboard.el
or
1. Download init-onboard.el
2. Put this in your Emacs init file: ~(require 'init-onboard "~/path/to/init-onboard.el")~
3. Start Emacs

** Tested with:

- Emacs 27.1 on Ubuntu 20.04 LTS
- Emacs 26.1 on Debian 10.9.0

** Getting comfortable

"F12" Toggle between dark and light theme

"C-g" Get out! Press <Ctrl>-<g> to cancel whatever happens (or 3x <ESC>)

"C-h o" Place the point ("cursor") on a function, variable, or other symbol and press the key binding to view documentation

"M-;" Comment/uncomment selected code

"M-x" Execute command: Press <Alt>-<x> to reach all available commands

Examples:

"M-x list-packages" Install 3rd-party packages ("app store"/"marketplace")

"M-x check-parens" Check if all parens match (in Emacs Lisp code file)

"M-x load-file" Load and execute (!) files with Emacs Lisp code


