* 🚀 ONBOARD – Build your own vanilla Emacs

*Portable Emacs config without any 3rd-party packages*

Overwhelmed by the complexity of (excellent) Emacs starter distributions like Doom-Emacs or Spacemacs?
You want to build your Emacs config bottom-up but not forget easy-to-miss basics?

The goal of this Emacs config is to offer a beginner-friendly, clean slate to build upon. It stays as close as possible to vanilla Emacs, but offers some convenience and a better look, without relying on other packages. It's all built-in – all ONBOARD.

** Why, oh why? Yet another Emacs starter kit?

Legit question. Well, better 69 roads to Emacs than 3-5, no? While I was setting up a VM to test some stuff, I wished I had a one-file-config that I can simply drop in, and have a sane environment in no time. An then, when I was cleaning up my Emacs config again, I realized that I haven't touched some parts within the last months or so. They just worked well.

So I stripped out those parts and put it all in one file, and made them my core config. Then added some grooming to make everything digestable for the public, and -- here we are.

Actually I use not just that config but have my Emacs config modularized into several -- e. g. an extension layer where 3rd-party packages are configured, configs for programming languages, etc. But this is the heart piece.

** Getting started (Linux)

*** New Emacs user without own config files?

1. Download [[https://raw.githubusercontent.com/monkeyjunglejuice/emacs-onboard/main/init-onboard.el][init-onboard.el]]
2. Rename it to =.emacs=
3. Move it to your home directory and start Emacs
or
1. Download [[https://raw.githubusercontent.com/monkeyjunglejuice/emacs-onboard/main/init-onboard.el][init-onboard.el]]
2. Rename it to =init.el=
3. Move it to =~/.emacs.d= directory and start Emacs

*** Emacs user with existing .emacs or ~/.emacs.d/init.el file?

1. Download [[https://raw.githubusercontent.com/monkeyjunglejuice/emacs-onboard/main/init-onboard.el][init-onboard.el]]
2. Open a terminal to try it out
3. Run the shell command: ~emacs -Q --load ~/path/to/init-onboard.el~
or
1. Download [[https://raw.githubusercontent.com/monkeyjunglejuice/emacs-onboard/main/init-onboard.el][init-onboard.el]]
2. Put this in your Emacs init file: ~(require 'init-onboard "~/path/to/init-onboard.el")~
3. Start Emacs


** Getting started (Windows)
- /Coming soon!/

** Tested with:

- [X] Emacs 27.1 on Ubuntu 20.04 LTS
- [X] Emacs 26.1 on Debian 10.9.0
- [ ] Emacs 27.1 on Windows 10
- [ ] Emacs 27.1 on MacOS

** Getting comfortable

If you are an Emacs beginner, you will find the most tips and answers in the file itself.

The seemingly weird keybindings are not what make Emacs. They are in fact secondary. All those keybindings are just convenience shortcuts to use commands, but they are not the commands themselves. The /commands/ are the really interesting things.

What that means:

*** There are just 2 keybindings that are really important:

<<<<<<< HEAD
"M-x" — Execute a command. Press <Alt>-<x> to reach all available commands.
=======
*"M-x"* – Execute a command. Press <Alt>-<x> to reach all available commands.
>>>>>>> 920ea843678924cce5df40e161cd2fa3130558cd

Examples:

- "M-x list-packages" Install 3rd-party packages (the "Emacs app store" or "Emacs marketplace" cough-cough)

- "M-x check-parens" Check if all parens match (in Emacs Lisp code file)

- "M-x help" to reach the ultimate help menu


*** And the other important keybinding is this:

<<<<<<< HEAD
"C-g" — Get out! Press <Ctrl>-<g> to cancel whatever happens (or 3x <ESC>, which is the same)
=======
*"C-g"* – Get out! Press <Ctrl>-<g> to cancel whatever happens (or 3x <ESC>, which is the same)
>>>>>>> 920ea843678924cce5df40e161cd2fa3130558cd
